name: Deploy to GitHub Packages

on:
  push:
    paths:
      - '*.py'
      - requirements.txt
    branches:
      - main
  workflow_dispatch:

jobs:
  github:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Download Arial
        run: wget https://github.com/matomo-org/travis-scripts/raw/master/fonts/Arial.ttf -O arial.ttf

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/darmiel/more-jpeg:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}